version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - 27018:27017
    volumes:
      - mongo-data:/data/db

  nest-app:
    build: .
    container_name: nest-app
    restart: always
    ports:
      - 3100:3000
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/film_finder
      NODE_ENV: docker
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start

volumes:
  mongo-data:
